version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=thorkran
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql

  api:
    image: node:20
    restart: always
    environment:
      - PORT=9898
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=thorkran
    ports:
      - '9898:9898'
    volumes:
      - .:/mnt
    working_dir: /mnt
    command: npm run start-api
